# Generated by Django 3.2.5 on 2022-05-09 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_comments'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'verbose_name': 'Комментарии', 'verbose_name_plural': 'Комментарии'},
        ),
    ]
