# Generated by Django 3.2.5 on 2022-05-09 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_comments_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='recept_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.recepts'),
        ),
    ]
