# Generated by Django 3.2.5 on 2022-05-09 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_comments_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='count_comments',
            field=models.IntegerField(default=0),
        ),
    ]
